# Generated by Django 4.1.2 on 2022-10-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publishedDate',
            new_name='publishedAt',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updatedDate',
            new_name='updatedAt',
        ),
    ]
