# Generated by Django 4.1.2 on 2022-10-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_article_authorimage_article_excerpt_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
    ]
